version: '3.9'

services:
  envify-dbms:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./envify-dbms/.env.exemple
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
    ]
    volumes:
      - ./envify-dbms/dbms-data:/var/lib/mysql
      - ./envify-dbms/mariadb.cnf:/etc/mysql/mariadb.cnf
      - ./envify-dbms/dev-initdb.d:/docker-entrypoint-initdb.d
      - ./envify-dbms/ddl/ddl.sql:/docker-entrypoint-initdb.d/999-ddl.sql
    networks:
      - envify-network

networks:
  envify-network:
    driver: bridge
